version: '3.9'
#services 
services:
  # Server services
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: xfintern-server-contributor
    container_name: xfintern_backend_contributor
    volumes:
      - ./:/server
    ports:
      - "9009:9009"
    env_file: ./backend/config.env
    depends_on:
      - mongodb
    networks:
      - xfintern_network
  # Frontend Services
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: xfintern-client-contributor
    container_name: xfintern_frontend_contributor
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./:/client
    networks: 
      - xfintern_network
  # Mongodb Services
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    networks:
      - xfintern_network
    ports:
      - "27017:27017"

volumes:
  mongodb:


networks:
  xfintern_network:
