name: Jest Testing
on: push
jobs:
  jest:
   name: 'Jest testing'
   runs-on: ubuntu-22.04
   permissions: write-all
   steps:
    - uses: actions/checkout@v4
      with:
          node-version: '20.x'
    - name: Install Dependencies
      run: npm install
    - name: 'start testing'
      run: npm run test
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
    - name: Jest code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage/Icon-report
