name: Jest Testing
on: push
jobs:
  jest:
   name: 'Jest testing'
   runs-on: ubuntu-22.04
   defaults:
         run:
           working-directory: ./backend
   permissions: write-all
   steps:
    - uses: actions/checkout@v4
      with:
          node-version: '20.x'
    - name: Install Dependencies
      run: npm install
    - name: 'start testing'
      run: npm run test
    - name: Run eslint
      run: npm run eslint
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
    - name: Jest code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./coverage/Icon-report
  yaml-lint:
    name: yaml-lint
    runs-on: ubuntu-22.04
    defaults:
         run:
           working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - name: install yamllint
        run: sudo apt-get install -y yamllint
      - name: Run yamllint
        run: yamllint .
